### ISSUE TITLE
Elección de gestor de tareas

### ISSUE THREAD

**Issue by vdeq79** [vdeq79/Projecto-XSZ#10]
Para el gestor de tareas, el criterio que se ha impuesto es la variedad de tareas que pueden hacer ( en algunos casos, plugins que les permiten realizar tareas) y se ha tenido en cuenta las siguientes posibilidades:

- **Grunt**: es una herramienta que permite simplificar el proceso de construcción de proyectos. Permite tareas como control de calidad (JSLint), la ofuscación, compilación o testing de unidades, entre otros. A día de hoy, tiene 6250 plugins que definen tareas tales que sólo hay que configurarlos para utilizarlos. 
- **Gulp**: aprovecha de la flexibilidad de JavaScript, es simple, eficiente y proporciona rapidez y precisión. Define las tareas a partir de declaraciones de funciones de JavaScript en un fichero llamado Gulpfile.fs. A día de hoy, tiene 4249 plugins, ligeramente menor que Grunt, sin embargo no es escaso.
- **Make**: es una herramienta general que aparte de generar archivos a partir de otros y permite realizar otras operaciones como ejecutar otras herramientas o comandos. A diferencia de gulp o grunt, no necesita plugins o runtime de JavaScript, por ello, no tiene funcionalidades particulares dedicadas al desarrollo de un proyecto de JavaScript.

Finalmente se ha optado por utilizar Grunt por tener una amplia variedad de tareas definidas orientadas a JavaScript (por ejemplo, _Concat_ que permite concatenar varios ficheros o _ImageMin_ que permite reducir el tamaño de archivos imágenes).

**Comment by dmonjasm** [comment]
No estoy familiarizado con Grunt pero buscaré documentación y me pondré un poco al día. 

Respecto al objetivo que estás desarrollando, ¿es el 2 no?, porque he estado mirando las ramas creadas y no he visto la del Objetivo 2.

**Comment by vdeq79** [comment]
> No estoy familiarizado con Grunt pero buscaré documentación y me pondré un poco al día.
> 
> Respecto al objetivo que estás desarrollando, ¿es el 2 no?, porque he estado mirando las ramas creadas y no he visto la del Objetivo 2.

Tanto este issue como el de gestor de dependencias corresponden al Objetivo 3, asi que no te preocupes.
