### ISSUE TITLE
Estructura de proyecto

### ISSUE THREAD

**Issue by dmonjasm** [vdeq79/Projecto-XSZ#12]
He estado buscando buenas prácticas de como estructurar un proyecto en TypeScript y no he encontrado una estructura claramente definida más allá a de un directorio src. Cómo quieres estructurar el proyecto?. Mi idea inicial es:

```
LICENSE
README
iv.yaml
tsconfig.json
package.json
docs/*
src/
- lista_usuario.ts
- anime.ts
```

Esta configuración la he visto aquí [typescript project directory](https://plainenglish.io/blog/typescript-project-directory-structure-module-resolution-and-related-configuration-options).

**Comment by vdeq79** [comment]
Es suficiente con que creas las clases dentro de la carpeta scr.
