### ISSUE TITLE
Opciones iniciales tsconfig.json (Relacionado con #12)

### ISSUE THREAD

**Issue by dmonjasm** [vdeq79/Projecto-XSZ#13]
Visto lo comentado en #12 habría que ver cual es la configuración inicial que se quiere incluir en tsconfig.json.

Un par de ejemplos básicos se pueden ver en esta página [ejemplos](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html).

**Comment by dmonjasm** [comment]
Aunque esto no sé si quedaría incluido en este Objetivo-2

**Comment by vdeq79** [comment]
Esto no es propio del objetivo 2, lo puedo abordar más adelante cuando necesite incluir más códigos.
