### ISSUE TITLE
Lenguaje de programación

### ISSUE THREAD

**Issue by dmonjasm** [vdeq79/Projecto-XSZ#6]
He creado el issue para ver que lenguaje tenías pensado utilizar. He visto que has mencionado la API Jikan, luego intuyo que tienes pensado usar PHP.

**Comment by vdeq79** [comment]
Hola, he pensado usar TypeScript (que es un superconjunto de JavaScript) para desarrrollar el proyecto (que es la que estoy usando para el objetivo 2 también). El API Jikan está implementado en PHP pero tiene integraciones para TypeScript.

**Comment by dmonjasm** [comment]
De acuerdo. La verdad que no conozco nada de TypeScript pero le voy  a echar un ojo a la documentación a ver como funciona. Abriré otro issue para el tema del modelado de la aplicación.

**Comment by vdeq79** [comment]
Yo tampoco tengo muchos conocimientos de TypeScript (sí algo de JavaScript), de todos modos, te paso este link que también me ha pasado a mí: https://jj.github.io/IV/documentos/proyecto/2.Entidad.recursos.html.

**Comment by JJ** [comment]
¿Habéis solucionado algo con esto? ¿Algún problema para seguir con el resto de los issues para hacer el PR?

**Comment by dmonjasm** [comment]
Me he leído este finde semana un poco la docu de TypeScript que pasaste y lo veo bien. Asique ahora abro un issue para ver cómo modelar el proyecto. Cuando me confirmes lo creo.

**Comment by vdeq79** [comment]
👍🏻

**Comment by JJ** [comment]
Si cierras desde el interfaz, te van a dar error siempre todos los tests. No se cierra nunca desde el interfaz, siempre desde un commit. En este caso, el que se hace en el PR, o el mismo PR. Esto lo he repetido en clase varias veces. Os rogaría que prestárais atención a estas cosas para evitar problemas futuros.

**Comment by vdeq79** [comment]
Vaya, se me había pasado. Si reabro desde la interfaz, ¿siguirán dando error en los tests?

**Comment by JJ** [comment]
No. Pero tendrás que cerrarlo desde un commit o PR.
