### ISSUE TITLE
Entidades

### ISSUE THREAD

**Issue by dmonjasm** [vdeq79/Projecto-XSZ#7]
Viendo los *milestones* y historias de usuario se me ocurre una única entidad que sería el perfil de usuario o lista de usuario. En ella se tendrían los animes que ha visto o está viendo un usuario, así como un perfil de los gustos de la persona (que no se muy bien como se podría modelar)

Por otro lado en cuanto a los objetos valor sólo se me ocurre:
- Anime

No se que tenías tu pensado, me vas diciendo

**Comment by vdeq79** [comment]
Coincido contigo con que la entidad sería las **listas de animes del usuario** con sus animes vistos (separados por el estado, es decir, vistos, a medias, dejadas) y **Anime** sería objeto valor ya que la lógica de negocio se aplicaría a todo el conjunto y no a un anime en concreto.

**Comment by dmonjasm** [comment]
Perfecto. A parte de esta entidad y este objeto valor se te ocurre alguno más?.

**Comment by vdeq79** [comment]
Creo que con esas dos clases sería suficiente para aplicar la lógica de negocio y abordar el proyecto.

**Comment by dmonjasm** [comment]
La entidad claramente tendrá que tener un array o un diccionario de animes. Aparte de este atributo que más atributos se le pondrían para poder representar la lógica de negocio?
