### ISSUE TITLE
Objetos-valor

### ISSUE THREAD

**Issue by dmonjasm** [vdeq79/Projecto-XSZ#8]
Como hemos hablado en #7, sólo se me ocurre el objeto valor **Anime** y así de primeras le pondría estos atributos:
- Número de capítulos
- Genero (puede tener varios géneros)
- Estado (finalizado, en emisión, cancelado...)
- ¿Fecha de emisión? (en caso de que el anime esté en emisión se indica que día se emite el capítulo)

**Comment by vdeq79** [comment]
Como tenía pensado usar la API de Jikan para extraer los datos, aquí te dejo un enlace del JSON que devuelve dicha API: https://api.jikan.moe/v4/anime/38000/full. No necesito todos esos datos, pero sí los datos de interés como los que has mencionado. Sugeriría tener un diccionario para los títulos, ya que como puedes ver en el JSON, dependiendo del idioma el título varía. También tener campo para studios (que pueden ser varios) que han participado en la realización del anime ya que puede influir en la lógica de negocio.

**Comment by vdeq79** [comment]
Para el título cogería el default como viene en la API, aunque pienso que es interesante considerar todos por si el usuario introduce un título escrito en otro idioma.

**Comment by dmonjasm** [comment]
Finalmente para el objeto valor anime he considerado los siguientes campos:
- titles
- synopsis
- episodes
- type
- status
- genres
- year
- broadcast

Creo que con estos se cumplen de sobra los requisitos para #5, #4 y #3

**Comment by dmonjasm** [comment]
Los he sacado del json que me mandaste que devolvía jikan. Si hay alguno más que quieras añadir me dices
